<?php

declare(strict_types=1);

/**
 * The nine projects that fill the MySQL database.
 * Served by the PHP backend (/api/projects) to the React frontend.
 */
return [
    [
        'slug'       => 'gold-poster',
        'title'      => 'Automated Gold Poster Application',
        'category'   => 'SaaS Product',
        'short_desc' => 'Automated marketing & daily rate poster generator for jewelry showrooms with live market gold price sync.',
        'full_desc'  => 'Inwora Gold Poster is a specialized SaaS branding and marketing automation app engineered specifically for premier jewelry showrooms. Every morning, the application automatically fetches live market bullion prices (24K, 22K, 18K gold and silver) and embeds them onto high-resolution luxury promotional templates dynamically customized with your showroom logo, address, tagline, and contact numbers. Showroom owners can generate daily branded posters in one tap, export zero-watermark graphics directly to WhatsApp Status and Instagram Stories, and receive 10 ready-to-post AI promotional video reels every month — completely eliminating manual graphic design costs and saving hours of daily administrative work.',
        'icon'       => 'Layout',
        'banner'     => '/assets/projects/gold-poster.png',
        'video_url'  => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        'pdf_url'    => '/assets/pdf/gold-poster-presentation.pdf',
        'live_url'   => 'https://gold.inwora.com',
        'tags'       => ['React', 'SaaS', 'Jewelry Tech', 'Marketing Automation'],
        'features'   => [
            'Real-time Gold & Silver Rate Integration',
            'Automated High-Res Image Generator',
            'One-click WhatsApp & Instagram Export',
            'Bulk Poster & Story Generation',
            '10 Monthly AI Showroom Video Reels',
            'Dynamic Brand Kit & Logo Overlay',
        ],
    ],
    [
        'slug'       => 'pos-kot',
        'title'      => 'POS & KOT for Restaurants',
        'category'   => 'Business Software',
        'short_desc' => 'Integrated Point-of-Sale billing, table management, and live Kitchen Order Ticket (KOT) workflow system.',
        'full_desc'  => 'POS & KOT for Restaurants is an enterprise-grade dining outlet management system designed to bridge table order booking counters directly with the kitchen. Built for fast-paced restaurants, cafes, and multi-outlet dining chains, waitstaff can enter table orders on mobile tablets, which instantly sync onto Kitchen Display System (KDS) screens and print thermal Kitchen Order Tickets (KOT) in real time. It features split billing, captain management, inventory depletion tracking, thermal receipt printing, and automated end-of-day financial reconciliation reports.',
        'icon'       => 'Database',
        'banner'     => '/assets/projects/pos-kot.png',
        'video_url'  => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        'pdf_url'    => '/assets/pdf/nexora-pos-deck.pdf',
        'live_url'   => 'https://kot.nexoraapp.in/',
        'tags'       => ['Real-time Sync', 'POS Billing', 'KOT System', 'Analytics'],
        'features'   => [
            'Real-time Kitchen Display System (KDS)',
            'Thermal Receipt Printer Integration',
            'Table & Captain Order Tablet Management',
            'Offline Billing & Data Recovery',
            'Daily Financial Reconciliation Reports',
            'Recipe Costing & Inventory Tracking',
        ],
    ],
    [
        'slug'       => 'hospital-management',
        'title'      => 'Hospital Management Application',
        'category'   => 'Healthcare System',
        'short_desc' => 'HIPAA-compliant healthcare portal for Electronic Health Records (EHR), doctor scheduling, and medical billing.',
        'full_desc'  => 'The Hospital Management Application is a secure, HIPAA-compliant digital healthcare portal created to streamline clinical operations and patient care. It manages end-to-end hospital administrative workflows, including patient registration, OPD/IPD admission logs, doctor appointment scheduling calendars, and Electronic Health Record (EHR) maintenance. The platform automates lab test report dispatches, ward bed allocations, and itemized medical billing claims, empowering clinical staff and physicians to deliver coordinated, error-free patient care.',
        'icon'       => 'Activity',
        'banner'     => '/assets/projects/hospital-management.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['EHR System', 'HIPAA Compliant', 'React', 'Node.js'],
        'features'   => [
            'Electronic Health Records (EHR)',
            'Doctor Appointment Scheduler Calendar',
            'Ward & ICU Bed Occupancy Management',
            'Automated Laboratory Test Reports',
            'Medical Billing & Insurance Claim Sync',
            'Secure Staff Clinical Communications',
        ],
    ],
    [
        'slug'       => 'factory-automation',
        'title'      => 'Automated Factory Application',
        'category'   => 'Industrial Solutions',
        'short_desc' => 'Smart Industry 4.0 factory floor control dashboard with real-time IoT machinery monitoring and quality checks.',
        'full_desc'  => 'The Automated Factory Application is a custom Industry 4.0 industrial IoT monitoring platform built for modern manufacturing plants and assembly lines. By connecting PLC controllers and wireless MQTT sensors directly to centralized management dashboards, the system tracks real-time machine operating status, assembly line throughput, temperature/vibration metrics, and Overall Equipment Effectiveness (OEE). It automatically triggers predictive maintenance alarms before breakdowns occur, reducing factory assembly downtime by 90% and eliminating manual paper logs.',
        'icon'       => 'Code',
        'banner'     => '/assets/projects/factory-automation.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['IoT', 'Factory Floor', 'Automation', 'MQTT'],
        'features'   => [
            'Real-Time Machinery Status Telemetry',
            'Predictive Maintenance Alarms',
            'Shift Assembly Throughput Tracking',
            'Automated Quality Control Checkpoints',
            'Barcode & RFID Label Scanner',
            'PLC & MQTT Industrial Integration',
        ],
    ],
    [
        'slug'       => 'travel-budget',
        'title'      => 'Travel Budget Application',
        'category'   => 'Financial Tool',
        'short_desc' => 'Multi-currency travel expense tracker, receipt scanner, and visual itinerary cost planner for teams and travelers.',
        'full_desc'  => 'The Travel Budget Application is a smart fintech tool designed for leisure travelers and corporate business teams to track expenditures, set category budgets, and prevent overspending while on the road. Integrated with live auto-converting currency exchange rates, the application allows users to split expenses across accommodation, flights, transportation, and dining. Travelers can scan physical paper receipts via OCR, view visual itinerary budget maps, and divide group trip expenses seamlessly offline and online.',
        'icon'       => 'Compass',
        'banner'     => '/assets/projects/travel-budget.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['Fintech', 'Expense Tracker', 'Multi-Currency', 'Mobile App'],
        'features'   => [
            '150+ Currency Live Auto-Conversion',
            'Visual Trip Itinerary Cost Builder',
            'OCR Receipt Image Scanning',
            'Group Expense Splitting & Settlement',
            'Category Spending Limit Alerts',
            'Offline Data Sync Enabled',
        ],
    ],
    [
        'slug'       => 'construction-crm',
        'title'      => 'Construction CRM',
        'category'   => 'SaaS Product',
        'short_desc' => 'Dedicated CRM for construction groups to track client bids, contractor materials, and work site progress.',
        'full_desc'  => 'Construction CRM is a specialized contractor CRM platform tailored to handle the unique workflows of general contractors, commercial builders, and civil engineering groups. It centralizes contractor directories, tracks construction bid progress, manages building material procurement orders, and hosts client communication boards. Site managers can upload daily site pictures and inspection logs to update property owners on build milestones, weather conditions, and progress billing cycles.',
        'icon'       => 'HardHat',
        'banner'     => '/assets/projects/construction-crm.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['Contractor Tool', 'CRM', 'Bid Tracker', 'Civil Eng'],
        'features'   => [
            'Bid & Cost Estimate Builder',
            'Building Material Procurement Tracker',
            'Daily Work Site Inspection Photo Logs',
            'Subcontractor Work Directory',
            'Milestone Progress Billing Cycles',
            'Live Site Weather Sync & Logs',
        ],
    ],
    [
        'slug'       => 'lead-management',
        'title'      => 'Lead Management System',
        'category'   => 'SaaS Product',
        'short_desc' => 'Growth-centric sales funnel to capture, score, route, and convert B2B leads across digital marketing channels.',
        'full_desc'  => 'The Lead Management System is a B2B sales automation CRM engineered to track business leads from initial digital capture through final deal conversion. Featuring an interactive Kanban pipeline board, the platform ranks incoming leads using an automated lead-scoring algorithm based on engagement levels and buyer intent. It automatically routes high-value prospects to appropriate sales reps, triggers SLA follow-up alerts, tracks email campaign open rates, and provides detailed sales velocity analytics.',
        'icon'       => 'Globe',
        'banner'     => '/assets/projects/lead-management.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['Lead Nurturing', 'Sales Funnel', 'Automation', 'CRM Integrations'],
        'features'   => [
            'Automated Multi-Channel Lead Capture',
            'Lead Scoring & Intent Algorithm',
            'SLA Rep Follow-up Alerts',
            'Email Campaign Engagement Tracking',
            'Interactive Kanban Pipeline Board',
            'Detailed Sales Velocity Analytics',
        ],
    ],
    [
        'slug'       => 'scrom-lms',
        'title'      => 'SCORM LMS Learning Management System',
        'category'   => 'EdTech Portal',
        'short_desc' => 'SCORM-compliant e-learning digital academy for interactive course delivery, student tracking, and auto-certification.',
        'full_desc'  => 'Our SCORM LMS is a digital learning academy portal built for educational institutions and corporate training programs. Built around SCORM 2004 standards, it seamlessly imports standardized e-learning course packages, maintaining precise logs on student module completion times, quiz scores, and learning progress metrics. Instructors can build interactive quizzes, monitor class analytics, and issue automated, verified graduation certificates upon successful course completion.',
        'icon'       => 'GraduationCap',
        'banner'     => '/assets/projects/scrom-lms.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['SCORM Compliant', 'LMS', 'E-Learning', 'Certification'],
        'features'   => [
            'Standard SCORM 2004 Package Import',
            'Real-Time Student Completion Tracker',
            'Interactive Quiz & Exam Builders',
            'Auto Verification Certificate Issuance',
            'Instructor Class Performance Dashboards',
            'Course Access & Enrollment Controls',
        ],
    ],
    [
        'slug'       => 'accounts-management',
        'title'      => 'Accounts Management System',
        'category'   => 'Financial Tool',
        'short_desc' => 'Double-entry financial accounting software with automated invoicing, ledger tracking, and tax reconciliation.',
        'full_desc'  => 'The Accounts Management System is a secure, double-entry financial accounting platform designed for small-to-medium enterprises. It automates general financial ledger updates, tracks recurring operating expenses, generates and dispatches professional PDF invoices to clients, and compiles instant Profit & Loss (P&L) financial statements. The system streamlines bank account reconciliations and tax category mapping, saving business owners and accountants over 70% in administrative preparation time.',
        'icon'       => 'Calculator',
        'banner'     => '/assets/projects/accounts-management.png',
        'video_url'  => null,
        'pdf_url'    => null,
        'live_url'   => null,
        'tags'       => ['Accounting', 'Invoicing', 'Tax Prep', 'Double-Entry'],
        'features'   => [
            'Automated PDF Invoice Dispatch',
            'Double-Entry General Ledger Balance',
            'Bank Statement Auto-Reconciliation',
            'Instant P&L Financial Statement Generator',
            'Automated Tax Category Mapping',
            'Secure Accountant Access & Audit Trail',
        ],
    ],
];
